name: hdl
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  font_awesome_flutter: ^10.2.1
  table_calendar:  ^3.0.8
  lottie:  ^2.0.0
  dio:  ^4.0.6
  http: ^1.1.0
  rating_dialog:  ^2.0.4
  shared_preferences:  ^2.0.15
  provider:  ^6.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/succ.json
